### ISSUE TITLE
Error in modeling_create_smoment_model.py

### ISSUE THREAD

**Issue by arendma** [klamt-lab/autopacmen#22]
Hey @Paulocracy, 

I am trying to run the sMOMENT model generation and get a KeyError and a "need to pass list" warning during the call to modeling_create_smoment_model.py: 

<pre><code>
    /home/miniconda3/envs/apacmen/lib/python3.8/site-packages/cobra/core/group.py:107: UserWarning: need to pass in a list
    warn("need to pass in a list")
    Traceback (most recent call last):
    File "modeling_create_smoment_model.py", line 93, in <module>
      create_smoment_model_cli()
    File "/home/miniconda3/envs/apacmen/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
      return self.main(*args, **kwargs)
    File "/home/miniconda3/envs/apacmen/lib/python3.8/site-packages/click/core.py", line 1062, in main
      rv = self.invoke(ctx)
    File "/home/miniconda3/envs/apacmen/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/miniconda3/envs/apacmen/lib/python3.8/site-packages/click/core.py", line 763, in invoke
      return __callback(*args, **kwargs)
    File "modeling_create_smoment_model.py", line 84, in create_smoment_model_cli
       create_smoment_model_reaction_wise_with_sbml(input_sbml_path, output_sbml_name, project_folder, project_name,
    File "/home/Software/autopacmen/autopacmen/submodules/create_smoment_model_reaction_wise.py", line 337, in create_smoment_model_reaction_wise_with_sbml
      create_smoment_model_reaction_wise(model, output_sbml_name,
    File "/home/Software/autopacmen/autopacmen/submodules/create_smoment_model_reaction_wise.py", line 267, in create_smoment_model_reaction_wise
      number_units = reaction_id_gene_rules_protein_stoichiometry_mapping[
    KeyError: 'A0A2K3DYJ4'
</code></pre>

Since this is the first reaction linked to a single gene / homoeric enzyme I think it has to do something with the parsing of GPR rules. Thanks a lot for designing this tool and for your help!

**Comment by Paulocracy** [comment]
Hello!
First of all sorry for my late reply (which happens far too often by me :3), I've been sick for several weeks :-| But regarding your issue, it looks like A0A2K3DYJ4 cannot be found in the *_enzyme_stoichiometries.xlsx. Can you check if A0A2K3DYJ4 appears there and, if this is the case, if it has attached gene rules as depicted in the attached example image from iJO1366star's xlsx?
<img width="587" alt="Table" src="https://user-images.githubusercontent.com/36934614/178704416-c6389ff9-2f44-48c0-8756-e480007fdb94.PNG">

**Comment by Paulocracy** [comment]
See #27
